dist: trusty

matrix:
  include:
    - language: node_js
      node_js:
        - "8.11"
      script:
        - ./client/npm run build
    - language: java
      jdk: openjdk8
      script:
        - ./api/gradlew build