dist: trusty

matrix:
  include:
    - language: node_js
      node_js:
        - "6.1.0"
      before_script: cd client
      script:
        - npm install
        - npm run build
    - language: java
      jdk: openjdk8
      script:
        - ./api/gradlew build