export const DELETE_BOOK = 'DELETE_BOOK'
export const UPDATE_BOOK = 'UPDATE_BOOK'
export const GET_BOOK = 'GET_BOOK'
export const FETCH_BOOKS = 'FETCH_BOOKS'
export const DISPLAY_BOOKS = 'DISPLAY_BOOKS'
export const SHOW_ADD_NEW_BOOK = 'SHOW_ADD_NEW_BOOK'
export const HIDE_ADD_NEW_BOOK = 'HIDE_ADD_NEW_BOOK'
export const SET_NEW_BOOK_PROPS = 'SET_NEW_BOOK_PROPS'
export const UPDATE_VALIDATION_ERRORS = 'UPDATE_VALIDATION_ERRORS'
export const RESET_NEW_BOOK_PROPS = 'RESET_NEW_BOOK_PROPS'

export const FETCH_AUTHORS = 'FETCH_AUTHORS'
export const DISPLAY_AUTHORS = 'DISPLAY_AUTHORS'

