server:
  port: 8080
  error:
    whitelabel:
      enabled: false
spring:
  datasource:
    platform: h2
  data:
    rest:
      base-path: /api/v1
  profiles:
    active:
    - DEV
    #- LOCAL-DEV    
security:
  basic:
    enabled: false
my:
  cross-origins:
   allowed: http://localhost:3000



