insert into author(first_name, last_name) values ('Yakov', 'Fain')
insert into author(first_name, last_name) values ('Brian', 'Goetz')
insert into author(first_name, last_name) values ('Martin', 'Fowler')
insert into author(first_name, last_name) values ('Sam', 'Newman')
insert into author(first_name, last_name) values ('Tom', 'DeMarco')
insert into author(first_name, last_name) values ('Rober', 'C. Martin')
insert into author(first_name, last_name) values ('Rajesh', 'RV')
insert into author(first_name, last_name) values ('Noel', 'Markham')
insert into author(first_name, last_name) values ('Tomek', 'Kaczanowski')
insert into author(first_name, last_name) values ('Walter', 'Isaacson')
insert into author(first_name, last_name) values ('Stoyan', 'Stefanov')
insert into book(name,isbn,published,description,author_id) values ('Enterprise Web Development: Building HTML5 Applications', '1449356818','2014-07-28','JavaScript Developer Guide to Programming for Multiple Devices',1)
insert into book(name,isbn,published,description,author_id) values ('Java Concurrency in Practice', '0321349601','2006-05-19','Comprehensive coverage on one of the most advanced topics in Java',1)
