insert into author(first_name, last_name) values ('Yakov', 'Fain')
insert into author(first_name, last_name) values ('Brian', 'Goetz')
insert into author(first_name, last_name) values ('Martin', 'Fowler')
insert into author(first_name, last_name) values ('Sam', 'Newman')
insert into author(first_name, last_name) values ('Tom', 'DeMarco')
insert into author(first_name, last_name) values ('Rober', 'C. Martin')
insert into author(first_name, last_name) values ('Rajesh', 'RV')
insert into author(first_name, last_name) values ('Noel', 'Markham')
insert into author(first_name, last_name) values ('Tomek', 'Kaczanowski')
insert into author(first_name, last_name) values ('Walter', 'Isaacson')
insert into author(first_name, last_name) values ('Stoyan', 'Stefanov')