insert into author(first_name, last_name) values ('Yakov', 'Fain')
insert into author(first_name, last_name) values ('Brian', 'Goetz')
insert into author(first_name, last_name) values ('Martin', 'Fowler')
insert into author(first_name, last_name) values ('Sam', 'Newman')
insert into author(first_name, last_name) values ('Tom', 'DeMarco')
insert into author(first_name, last_name) values ('Rober', 'C. Martin')
insert into author(first_name, last_name) values ('Rajesh', 'RV')
insert into author(first_name, last_name) values ('Noel', 'Markham')
insert into author(first_name, last_name) values ('Tomek', 'Kaczanowski')
insert into author(first_name, last_name) values ('Walter', 'Isaacson')
insert into author(first_name, last_name) values ('Stoyan', 'Stefanov')
insert into book(name,isbn,published,description,author_id) values ('Enterprise Web Development: Building HTML5 Applications', '1449356818','2014-07-28','JavaScript Developer Guide to Programming for Multiple Devices',1)
insert into book(name,isbn,published,description,author_id) values ('Java Concurrency in Practice', '0321349601','2006-05-19','Comprehensive coverage on one of the most advanced topics in Java',2)
insert into book(name,isbn,published,description,author_id) values ('Refactoring: Improving the Design of Existing Code', '0201485672','1999-07-28','Code refactoring',3)
insert into book(name,isbn,published,description,author_id) values ('Building Microservices: Designing Fine-Grained Systems', '1491950358','2015-02-20','Microservices',4)
insert into book(name,isbn,published,description,author_id) values ('Patterns of Enterprise Application Architecture', '0321127420','2002-11-05','Patterns',3)
insert into book(name,isbn,published,description,author_id) values ('Domain-Specific Languages', '0321712943','2010-09-23','DSL',3)
insert into book(name,isbn,published,description,author_id) values ('Angular 2 Development with TypeScript', '1617293121','2016-12-04','Angular',1)
insert into book(name,isbn,published,description,author_id) values ('Spring Microservices', '1786466686','2016-06-28','Microservice adn Spring',7)
insert into book(name,isbn,published,description,author_id) values ('Java Programming Interviews Exposed', '1118722868','2014-02-17','Java Programming Interviews Exposed is written to specifically prepare you for the questions you will face when interviewing for highly sought-after jobs in Java',8)
